/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author Admin
 */
public class QuanLyQuanNhanJPanel extends javax.swing.JPanel {

    JScrollPane ScrollPane;
    JTable tblQuanNhan;
    private final String[] COLUMNS = {"Mã quân nhân",
        "Họ & tên",
        "Cấp hàm",
        "Ngày sinh",
        "Giới tính",
        "Nhập ngũ"};
    Object[][] data = {{"QN1", "Đỗ Thanh Vẹn", "Thượng Tá", "03/03/2003", "Nam", "01/01/2021"},
    {"QN2", "Nguyễn Quốc Thái", "Thượng Tá", "01/01/2003", "Nam", "01/01/2021"},
    {"QN3", "Nguyễn Yến Nương", "Thượng Tá", "01/01/2003", "Nữ", "01/01/2021"},
    {"QN4", "Trần Mộng Cơ", "Thượng Tá", "01/01/2003", "Nữ", "01/01/2021"}};

    void addTable() {
        pnlTable.setLayout(new BorderLayout());
        tblQuanNhan = new JTable(data, COLUMNS);
        TableColumn column = null;
        for (int i = 0; i < 6; i++) {
            column = tblQuanNhan.getColumnModel().getColumn(i);
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            tblQuanNhan.getTableHeader().setDefaultRenderer(centerRenderer);
            tblQuanNhan.getTableHeader().setForeground(Color.red);
            if (i == 1 || i == 3) {
                column.setPreferredWidth(70);
            } else {
                column.setPreferredWidth(50);
            }
            if (i == 0 || i == 2 || i == 3 || i == 4 || i == 5) {
                tblQuanNhan.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
        }
        ScrollPane = new JScrollPane(tblQuanNhan);
        pnlTable.add(ScrollPane, BorderLayout.CENTER);
        JTableHeader tblHeader = tblQuanNhan.getTableHeader();
        tblHeader.setBackground(Color.red);
    }

    /**
     * Creates new form QuanLyQuanNhanJPanel
     */
    public QuanLyQuanNhanJPanel() {
        initComponents();
        init();
        addTable();
    }

    void init() {
        txtTimKiem.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.GREEN));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        pnlTable = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(660, 550));

        pnlMain.setBackground(new java.awt.Color(240, 255, 66));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlMain.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 40));

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        pnlMain.add(pnlTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 660, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
