/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanel;

import Helper.ChuyenManHinh;
import JFrame.MainJFrame;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class TrangChuJPanel extends javax.swing.JPanel {

    void slideHeading() {
        Timer t = new Timer(10, new ActionListener() {
            int x = 0;
            int y = 520;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (x < 660) {
                    x++;
                    lblHeading.setLocation(x, y);
                } else {
                    x = -580;
                    lblHeading.setLocation(x, y);
                }
            }
        });
        t.start();
    }

    void slideShow() {
        Timer t = new Timer(600, new ActionListener() {
            int x = 0;
            String[] image = {"/Image/AnhQuanDoi/20267_Phong_Vang_mai_khuc_quan_hanh.jpg",
                "/Image/AnhQuanDoi/quan-doi-anh-hung-ttxvn.jpg",
                "/Image/AnhQuanDoi/86f669b2-1f49-414d-8301-b523b4a6df48.jpg"};

            @Override
            public void actionPerformed(ActionEvent e) {
                if (x == 2) {
                    lblImage.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().createImage(TrangChuJPanel.class.getResource(image[0])).getScaledInstance(660, 550, java.awt.Image.SCALE_SMOOTH)));
                }
                if (x == 5) {
                    lblImage.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().createImage(TrangChuJPanel.class.getResource(image[1])).getScaledInstance(660, 550, java.awt.Image.SCALE_SMOOTH)));
                }
                if (x == 8) {
                    lblImage.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().createImage(TrangChuJPanel.class.getResource(image[2])).getScaledInstance(660, 550, java.awt.Image.SCALE_SMOOTH)));
                }
                if (x == 11) {
                    x = 1;
                    lblImage.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().createImage(TrangChuJPanel.class.getResource(image[0])).getScaledInstance(660, 550, java.awt.Image.SCALE_SMOOTH)));
                }
                x++;
            }
        });
        t.start();
    }

    /**
     * Creates new form TrangChuJPanel
     */
    public TrangChuJPanel() {
        initComponents();
        this.setSize(660, 550);
        slideHeading();
        slideShow();
        lblImage.setIcon(new ImageIcon(Toolkit.getDefaultToolkit().createImage(TrangChuJPanel.class.getResource("/Image/AnhQuanDoi/co-do-viet-nam.jpg")).getScaledInstance(660, 550, java.awt.Image.SCALE_SMOOTH)));    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHeading.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 0, 0));
        lblHeading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/iconmonstr-star-filled-24.png"))); // NOI18N
        lblHeading.setText("NƯỚC CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM MUÔN NĂM!");
        jPanel1.add(lblHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 580, -1));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblImage;
    // End of variables declaration//GEN-END:variables
}
