/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import Helper.*;
import JavaClass.DanhMucChucNang;
import java.awt.Color;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import JPanel.*;

/**
 *
 * @author Admin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainJFrame() {
        initComponents();
        init();
    }
    
    void init() {
        this.setTitle("HỆ THỐNG QUẢN LÝ QUÂN SỰ");
        this.setLocationRelativeTo(null);
        addListChucNang();
        this.setSize(905, 588);
        Design();
    }
    
    void Design() {
        lblQuanLyQuanSu.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(240, 255, 66)));
    }
    
    void addListChucNang() {
        ChuyenManHinh controller = new ChuyenManHinh(pnlForm);
        controller.setView(pnlTrangChu, lblTrangChu);
        List<DanhMucChucNang> ListItem = new ArrayList<>();
        ListItem.add(new DanhMucChucNang("TrangChu", pnlTrangChu, lblTrangChu));
        ListItem.add(new DanhMucChucNang("QuanNhan", pnlQuanLyQuanNhan, lblQuanLyQuanNhan));
        ListItem.add(new DanhMucChucNang("QuanPhuc", pnlQuanLyQuanPhuc, lblQuanLyQuanPhuc));
        controller.setEvent(ListItem);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlQuanLyQuanSu = new javax.swing.JPanel();
        lblQuanLyQuanSu = new javax.swing.JLabel();
        pnlTrangChu = new javax.swing.JPanel();
        lblTrangChu = new javax.swing.JLabel();
        pnlQuanLyQuanPhuc = new javax.swing.JPanel();
        lblQuanLyQuanPhuc = new javax.swing.JLabel();
        pnlQuanLyQuanNhan = new javax.swing.JPanel();
        lblQuanLyQuanNhan = new javax.swing.JLabel();
        pnlForm = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(890, 550));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(130, 205, 71));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlQuanLyQuanSu.setBackground(new java.awt.Color(55, 146, 55));

        lblQuanLyQuanSu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQuanLyQuanSu.setForeground(new java.awt.Color(240, 255, 66));
        lblQuanLyQuanSu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuanLyQuanSu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/iconmonstr-star-filled-24.png"))); // NOI18N
        lblQuanLyQuanSu.setText("QUẢN LÝ QUÂN SỰ");

        javax.swing.GroupLayout pnlQuanLyQuanSuLayout = new javax.swing.GroupLayout(pnlQuanLyQuanSu);
        pnlQuanLyQuanSu.setLayout(pnlQuanLyQuanSuLayout);
        pnlQuanLyQuanSuLayout.setHorizontalGroup(
            pnlQuanLyQuanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuanLyQuanSu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        pnlQuanLyQuanSuLayout.setVerticalGroup(
            pnlQuanLyQuanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuanLyQuanSuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuanLyQuanSu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnlQuanLyQuanSu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, 50));

        pnlTrangChu.setBackground(new java.awt.Color(84, 180, 53));
        pnlTrangChu.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 0), null));
        pnlTrangChu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlTrangChuMouseMoved(evt);
            }
        });
        pnlTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlTrangChuMouseExited(evt);
            }
        });

        lblTrangChu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblTrangChu.setForeground(new java.awt.Color(240, 255, 66));
        lblTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/Home.png"))); // NOI18N
        lblTrangChu.setText("TRANG CHỦ");

        javax.swing.GroupLayout pnlTrangChuLayout = new javax.swing.GroupLayout(pnlTrangChu);
        pnlTrangChu.setLayout(pnlTrangChuLayout);
        pnlTrangChuLayout.setHorizontalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlTrangChuLayout.setVerticalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrangChuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnlTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 60, 204, 50));

        pnlQuanLyQuanPhuc.setBackground(new java.awt.Color(84, 180, 53));
        pnlQuanLyQuanPhuc.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 0), null));
        pnlQuanLyQuanPhuc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlQuanLyQuanPhucMouseMoved(evt);
            }
        });
        pnlQuanLyQuanPhuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlQuanLyQuanPhucMouseExited(evt);
            }
        });

        lblQuanLyQuanPhuc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQuanLyQuanPhuc.setForeground(new java.awt.Color(240, 255, 66));
        lblQuanLyQuanPhuc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQuanLyQuanPhuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/iconmonstr-clothing-3-24.png"))); // NOI18N
        lblQuanLyQuanPhuc.setText("QUẢN LÝ QUÂN PHỤC");

        javax.swing.GroupLayout pnlQuanLyQuanPhucLayout = new javax.swing.GroupLayout(pnlQuanLyQuanPhuc);
        pnlQuanLyQuanPhuc.setLayout(pnlQuanLyQuanPhucLayout);
        pnlQuanLyQuanPhucLayout.setHorizontalGroup(
            pnlQuanLyQuanPhucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuanLyQuanPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlQuanLyQuanPhucLayout.setVerticalGroup(
            pnlQuanLyQuanPhucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuanLyQuanPhucLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuanLyQuanPhuc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlQuanLyQuanPhuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 180, 204, -1));

        pnlQuanLyQuanNhan.setBackground(new java.awt.Color(84, 180, 53));
        pnlQuanLyQuanNhan.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 0), null));
        pnlQuanLyQuanNhan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlQuanLyQuanNhanMouseMoved(evt);
            }
        });
        pnlQuanLyQuanNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlQuanLyQuanNhanMouseExited(evt);
            }
        });

        lblQuanLyQuanNhan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblQuanLyQuanNhan.setForeground(new java.awt.Color(240, 255, 66));
        lblQuanLyQuanNhan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblQuanLyQuanNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon/User.png"))); // NOI18N
        lblQuanLyQuanNhan.setText("QUẢN LÝ QUÂN NHÂN");

        javax.swing.GroupLayout pnlQuanLyQuanNhanLayout = new javax.swing.GroupLayout(pnlQuanLyQuanNhan);
        pnlQuanLyQuanNhan.setLayout(pnlQuanLyQuanNhanLayout);
        pnlQuanLyQuanNhanLayout.setHorizontalGroup(
            pnlQuanLyQuanNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuanLyQuanNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        pnlQuanLyQuanNhanLayout.setVerticalGroup(
            pnlQuanLyQuanNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuanLyQuanNhanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuanLyQuanNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnlQuanLyQuanNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 120, 204, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 550));

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(pnlForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 660, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void EventMoved(JPanel panel, JLabel label) {
    }
    

    private void pnlQuanLyQuanPhucMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuanLyQuanPhucMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlQuanLyQuanPhucMouseMoved

    private void pnlQuanLyQuanPhucMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuanLyQuanPhucMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlQuanLyQuanPhucMouseExited

    private void pnlTrangChuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTrangChuMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTrangChuMouseMoved

    private void pnlTrangChuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTrangChuMouseExited
        // TODO add your handling code her
    }//GEN-LAST:event_pnlTrangChuMouseExited

    private void pnlQuanLyQuanNhanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuanLyQuanNhanMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlQuanLyQuanNhanMouseMoved

    private void pnlQuanLyQuanNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlQuanLyQuanNhanMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlQuanLyQuanNhanMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuanLyQuanNhan;
    private javax.swing.JLabel lblQuanLyQuanPhuc;
    private javax.swing.JLabel lblQuanLyQuanSu;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlQuanLyQuanNhan;
    private javax.swing.JPanel pnlQuanLyQuanPhuc;
    private javax.swing.JPanel pnlQuanLyQuanSu;
    private javax.swing.JPanel pnlTrangChu;
    // End of variables declaration//GEN-END:variables
}
